query Close($checkoutId: String!, $customerAccessToken: String!, $hasCustomerAccessToken: Boolean!) {
    checkout(checkoutId: $checkoutId, customerAccessToken: $customerAccessToken) {
        coupon
        couponDiscount
        customizationValue
        discount
        paymentFees
        totalDiscount
        subtotal
        total
        shippingFee
        checkingAccountValue
        checkingAccountActive
        selectedShipping{
            name
            value
            deadline
            deadlineInHours
            deliverySchedule{
                date
                endTime
                startTime
            }
        }
        selectedAddress{
            cep
            state
            city
            neighborhood
            addressNumber
            referencePoint
            complement
            street
        }
        products {
            productId
            productVariantId
            url
            listPrice
            price
            ajustedPrice
            imageUrl
            quantity
            name
            category
            gift
            kit
            customization{
                id
                values{
                    cost
                    name
                    value
                }
            }
            subscription{
                availableSubscriptions{
                    name
                    recurringDays
                    recurringTypeId
                    selected
                    subscriptionGroupDiscount
                    subscriptionGroupId
                }
                selected{
                    selected
                    name
                    recurringDays
                    recurringTypeId
                    subscriptionGroupDiscount
                    subscriptionGroupId
                }
            }
            productAttributes{
                name
                value
            }
        }
        kits {
            kitId
            kitGroupId
            alias
            imageUrl
            listPrice
            price
            totalListPrice
            totalAdjustedPrice
            name
            quantity
            products {
                productId
                productVariantId
                imageUrl
                name
                url
                quantity
                productAttributes {
                name
                value
                }
            }
        }
        formulaAdjustments{
            name
            value
        }
    }
    customer(customerAccessToken: $customerAccessToken) @include(if: $hasCustomerAccessToken) {
        customerId
        customerName
        customerType
        phoneNumber
        businessPhoneNumber
        cpf
        cnpj
        email
        checkingAccountBalance
        addresses{
            id
            cep
            country
            state
            city
            neighborhood
            address
            addressNumber
            addressDetails
            referencePoint
            name
        }
    }
}