query Confirmation(
  $checkoutId: String!
  $customerAccessToken: String!
  $hasCustomerAccessToken: Boolean!
) {
  checkout(checkoutId: $checkoutId) {
    checkoutId
    cep
    completed
    discount
    total
    subtotal
    shippingFee
    orders {
      date
      orderStatus
      orderStatusDisplay
      orderId
      totalValue
      discountValue
      shippingValue
      delivery {
        name
        deliveryTime
        address {
          address
          neighborhood
          city
          cep
        }
      }
      payments {
        name
        invoice {
          digitableLine
          paymentLink
        }
        pix {
          qrCode
          qrCodeExpirationDate
          qrCodeUrl
        }
        card {
          brand
          cardInterest
          installments
          name
          number
        }
        type
        value
        details {
          html
          scripts
        }
      }
      products {
        productVariantId
        name
        quantity
        value
        imageUrl
        attributes {
          name
          value
        }
      }      
    }
    formulaAdjustments{
      name
      value
    }
  }
  customer(customerAccessToken: $customerAccessToken)
    @include(if: $hasCustomerAccessToken) {
    customerId
    customerName
    customerType
    email
  }
}
