query Checkout($checkoutId: String!, $hasCheckout: Boolean!) {
  shop {
    checkoutUrl
  }  
  checkout(checkoutId:$checkoutId) @include(if: $hasCheckout) {
    checkoutId
    url
    metadata {
      key
      value
    }
    products {
      listPrice
      price
      ajustedPrice
      productId
      productVariantId
      imageUrl
      quantity
      name
      gift
      kit
      productAttributes{
        name
        type
        value
      }
      customization{
        id
        values{
          cost
          name
          value
        }
      }
    }
    kits {
      kitId
      kitGroupId
      alias
      imageUrl
      listPrice
      price
      totalListPrice
      totalAdjustedPrice
      name
      quantity
      products {
        productId
        productVariantId
        imageUrl
        name
        url
        quantity
        productAttributes {
          name
          value
        }
      }
    }
    shippingFee
    subtotal
    total
  }
}