query Home($partnerAccessToken: String){
  hotsite(url: "", partnerAccessToken: $partnerAccessToken) {
    banners {
      altText
      bannerName
      bannerUrl
      position
      urlOnClick
      openNewTab
      height
      title
      width
      order
    }
    contents {
      content
      height
      title
      width
      position
    }
    seo {
      content
      name
      type
      httpEquiv
      scheme
    }
  }
  lancamentos: search(query: "", partnerAccessToken: $partnerAccessToken) {
    ...lancamentos
  }
  maisVendidos: search(query: "", partnerAccessToken: $partnerAccessToken) {
    ...maisVendidos
  }
  maisOfertas: search(query: "", partnerAccessToken: $partnerAccessToken) {
    ...maisOfertas
  }
  brands(first: 10) {
    ...brands
  }
  newsletterInformationGroupFields {
    displayType
    fieldName
    id
    order
    required
    values{
      order
      value
    }
  }
}

fragment lancamentos on Search {
  products(first: 9, sortKey: RELEASE_DATE, sortDirection: DESC) {
    ...productsCon
  }
}

fragment maisVendidos on Search {
  products(first: 9, sortKey: SALES, sortDirection: DESC) {
    ...productsCon
  }
}

fragment maisOfertas on Search {
  products(first: 9, sortKey: DISCOUNT, sortDirection: DESC) {
    ...productsCon
  }
}

fragment productsCon on ProductsConnection {
  nodes {
    id
    productId
    productName
    productVariantId
    alias: aliasComplete
    freeShipping
    averageRating
    newRelease
    similarProducts{
      alias
      image
      name
      imageUrl(w: 50, h: 50)
    }
    images(width:275, height:275) {
      url
      print
    }
    available
    prices {
      listPrice
      price
      discountPercentage
      installmentPlans{
        displayName
        name
        installments{
          discount
          fees
          number
          value
        }
      }
      bestInstallment {
        name
        displayName
        discount
        fees
        number
        value
      }
    }
    promotions{
      content
      id
      stamp
      fullStampUrl
      title
      disclosureType
    }
    addToCartFromSpot
    productCategories {
      main
      name
    }
  }
}

fragment brands on BrandsConnection {
  nodes {
    active
    urlLogo
    alias
    fullUrlLogo(width:270)
    name
  }
}