query Account(
  $customerAccessToken: String!
  $hasCustomerAccessToken: Boolean!
  $orderId: Long
  $hasOrderId: Boolean!
) {
  customer(customerAccessToken: $customerAccessToken)
    @include(if: $hasCustomerAccessToken) {
    customerId
    customerName
    customerType
    email
    orders {
      totalCount
      page
      pageSize
      items {
        ...order
      }
    }
    order(orderId: $orderId) @include(if: $hasOrderId) {
      ...order
    }
  }
}

fragment order on order {
  coupon
  discount
  orderId
  date
  checkoutId @include(if: $hasOrderId)
  payments {
    total
    installments
    installmentValue
    paymentOption
    boleto {
      digitableLine
      paymentLink
    }
    pix {
      qrCode
      qrCodeExpirationDate
      qrCodeUrl
    }
  }
  total
  subtotal
  shippingFee
  status {
    status
    statusId
  }
  deliveryAddress @include(if: $hasOrderId) {
    receiverName
    street
    addressNumber
    city
    cep
    neighboorhood
    state
    referencePoint
    complement
    country
  }
  shippings {
    deadline
    deadlineText
    scheduleUntil
  }
  products {
    image
    name
    quantity
    unitaryValue
    salePrice
    price
    discount
    sku
    kit
    attributes {
      name
      value
    }
    adjusts {
      name
    }
  }
  kits {
    kitId
    kitGroupId
    alias
    imageUrl
    listPrice
    price
    totalListPrice
    name
    quantity
    products {
      name
      quantity
      image
      salePrice
      unitaryValue
      attributes{
        name
        value
      }
    }
  }
  trackings {
    code
    url
  }
}
